os: linux

dist: focal

language: c

python:
    - "3.9"

#sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:
    #- PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini --project-option='lib_ignore=2778,Wire,SPI'"
    - PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"
    # - PLATFORMIO_CI_SRC=test PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"

install:
    - pip install --user -U platformio
    # - platformio update
    - pio update

script:
    # - platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS
    - platformio run -e production ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS
    - platformio debug -e debug ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS
    - platformio test -e test ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS