os: linux

dist: focal

language: c

python:
    - "3.9"

#sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:
    #- PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini --project-option='lib_ignore=2778,Wire,SPI'"
    - PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"
    # - PLATFORMIO_CI_SRC=test PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y udev
  - curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
  - sudo udevadm control --reload-rules
  - sudo udevadm trigger
  - sudo usermod -a -G dialout travis

install:
    - pip install --user -U platformio
    # - platformio update
    - pio update

script:
    - platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS
    - platformio run -e production
    - platformio debug -e debug
    - platformio test -e test